version: "2"

run:
  tests: true
  modules-download-mode: readonly

formatters:
  enable:
    - gofmt
    - goimports
    - gofumpt
  settings:
    gofumpt:
      module-path: foodlist

linters:
  enable:
    - govet
    - staticcheck
    - gocritic
    - revive
  disable:
    - errcheck
    - godox
  settings:
    revive:
      severity: warning
      rules:
        - name: indent-error-flow
        - name: error-return
        - name: var-naming
  exclusions:
    rules:
      - text: should have comment
        linters:
          - revive

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
