version: "2"

run:
  timeout: 5m

linters:
  enable:
    - govet
    - staticcheck
    - gocritic
    - revive
  disable:
    - errcheck
    - godox
  settings:
    revive:
      rules:
        - name: indent-error-flow
        - name: error-return
        - name: var-naming

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
