version: 2

run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters:
  enable:
    - govet
    - staticcheck
    - gocritic
    - revive
  disable:
    - errcheck
    - godox

formatters:
  enable:
    - gofmt
    - goimports
    - gofumpt

linters-settings:
  gofumpt:
    module-path: gotodo
  revive:
    severity: warning
    rules:
      - name: indent-error-flow
      - name: error-return
      - name: var-naming

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude:
    - "should have comment"
